### PR TITLE
WIP package import that indirectly triggers importerror

### PR DESCRIPTION
**Pull request by dset0x**
When overlaying inveniosoftware/invenio, bad imports of this type were silently ignored, causing the registry to be missing files.

When mitsuhiko/werkzeug#735 lands, this will also point to the correct exception.

### CODE REVIEW

**Comment by lnielsen** [comment]
This has been a never ending issue with use of ``import_string`` which basically masks ``ImportError`` and ``AttributeError``. See also mitsuhiko/werkzeug#525. I'll be in GS tomorrow around lunch time, perhaps we sit down together to have a look, as I can't see if there's any potential issues as it's pretty hairy stuff.

**Comment by dset0x** [comment]
At some point it became so hard to make sense of what was going on that I took every case I could think of, wrote down all the information I could extract from each case and went by whatever rules arose from that information.

In other words: If we can think of more test cases: great.

---

I'll be around. Either very near or at my office (next to Jan's), or in R1.

**Comment by dset0x** [comment]
Turned this into a WIP: As it turns out, this fails without mitsuhiko/werkzeug#525 (which I had locally while testing on my box).

**Comment by dset0x** [comment]
I still haven't heard from the werkzeug folks. Regardless, it could be months until there is a release that includes my patch.

I believe however, that, for development, these patches could save a lot of time. Perhaps we could ship the new `import_string` ourselves?

Anyone feeling slightly adventurous could try:
* https://github.com/dset0x/flask-registry/tree/implicit_broken_module_import
* https://github.com/dset0x/werkzeug/tree/import_stacktrace

cc @jirikuncar @jalavik

**Comment by jirikuncar** [comment]
The PR has been stalled for year.

**Pull request closed without merging**
