### PR TITLE
pkgresources: advanced entry points

### PR DESCRIPTION
**Pull request by jirikuncar**
* Adds new options for `EntryPointRegistry`.
* Adds dependency checking based on indico/flask-pluginengine@ca9bb9067a66f4540389ca5759653711b6bc2997

--
cc @ThiefMaster @pferreir

### CODE REVIEW

**Comment by jirikuncar** [comment]
Hi, soon it will be one year since our last discussion about making Flask-Registry and Flask-PluginEngine to work together. Would this PR make it easier? What is it missing?

--
cc @lnielsen @ThiefMaster @pferreir @TimSmithCH

**Comment by pferreir** [comment]
IIRC what happened ~1yr ago, the agreement was that we need to sit down and figure out how feasible it would be to bring the two projects together, based on each project's own architecture and needs.

We definitely want (and there's space for that in next year's draft plan for that) to spend some time improving and documenting `flask-pluginengine` and `flask-multipass`. Before then, it would be great to have the discussion i mentioned above, a "bottom-up" analysis, based on each project's code, architecture and needs.

It's clear that a joint effort would be the ideal scenario (and there's a lot of potential for a fruitful collaboration), but that can only come after we all have a good understanding of what each project is doing and what are the common needs/points.

**Comment by TimSmithCH** [comment]
Pedro, I fully support your last paragraph, and would like to draw everyone's attention to the fact that I have tasked @jbenito3 with a short project to identify the areas of potential for common approaches, and shared codebases, so that we can efficiently plan next years developments in projects coherently

**Comment by jirikuncar** [comment]
I have updated the PR so it passes the tests however we don't need dependency checking with our new architecture in Invenio 3. You check how we are loading extensions in [Invenio-Base](https://github.com/inveniosoftware/invenio-base) using entry points only.

**Pull request merged**
